baseURL = "https://visionary-florentine-a4d51f.netlify.app/products/"
languageCode = "en-us"
title = "Awesome Lighting Inc."
theme = "hugo-shopping-product-catalogue-simple"
themesDir = "./themes"
[Params]
description = ""
GTMTAGID="GTM-KVRS8GJ3"
